// This file was generated by Prisma, and assumes you have installed the following:
// pnpm add --save-dev prisma dotenv
import { existsSync } from "node:fs";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

const envFile =
  process.env.PRISMA_ENV_FILE ??
  (process.env.APP_ENV === "production"
    ? ".env.production"
    : existsSync(".env.local")
      ? ".env.local"
      : ".env");

config({ path: envFile });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url:
      process.env.DIRECT_DATABASE_URL ||
      process.env.DATABASE_URL_UNPOOLED ||
      process.env.DATABASE_URL,
  },
});
