export const DAYS_OF_WEEK = [
  { value: "0", label: "Sunday" },
  { value: "1", label: "Monday" },
  { value: "2", label: "Tuesday" },
  { value: "3", label: "Wednesday" },
  { value: "4", label: "Thursday" },
  { value: "5", label: "Friday" },
  { value: "6", label: "Saturday" },
]

export const LANGUAGE_OPTIONS = [
  { value: "Filipino", label: "Filipino" },
  { value: "English", label: "English" },
  { value: "Cebuano", label: "Cebuano" },
  { value: "Ilocano", label: "Ilocano" },
  { value: "Hiligaynon", label: "Hiligaynon" },
  { value: "Waray", label: "Waray" },
  { value: "Kapampangan", label: "Kapampangan" },
  { value: "Bicolano", label: "Bicolano" },
]

export const CITY_OPTIONS = [
  "Caloocan",
  "Las Piñas",
  "Makati",
  "Malabon",
  "Mandaluyong",
  "Manila",
  "Marikina",
  "Muntinlupa",
  "Navotas",
  "Parañaque",
  "Pasay",
  "Pasig",
  "Pateros",
  "Quezon City",
  "San Juan",
  "Taguig",
  "Valenzuela",
  "Antipolo",
  "Bacoor",
  "Biñan",
  "Calamba",
  "Cavite City",
  "Imus",
  "Malolos",
  "Meycauayan",
  "San Fernando (Pampanga)",
  "San Pedro",
  "Santa Rosa",
  "Angeles",
  "Cebu City",
  "Davao City",
]
